### ISSUE TITLE
Issues plotting when more than 3 genes in the region

### ISSUE THREAD

**Issue by andrewcon** [Geeketics/LocusZooms#21]
Hi,

When I change the offset_bp variable to include more than 3 genes in the locus.zoom plot, it only displays the last three. e.g. If I plot a region with 6 genes, only the last 3 to appear are plotted.

I have tried rewriting some code in the functions, but nothing has worked so far.

Many thanks.

**Comment by Geeketics** [comment]
Hi, the offset_bp variable does not care where genes are/how many there are - it is solely based on the chromosome positions. If you want your plot to include all 6 genes you'll need to work out how far away they are from whatever you are centring your plot on (another gene, a SNP, etc) - it may be easier if you use the `region` option and specify exactly what chromosome positions you want on your plot.
If this doesn't help/doesn't make sense with what you're trying to do I'll need to see an example of what you're running + what you're aiming to see. :)

**Comment by andrewcon** [comment]
Hi, so I am running the following code:
`locus.zoom(data = mydata,
			   snp = snp_list[i],
			   ld.file = ld_plink,
			   offset_bp = 500000,
			   genes.data = UCSC_GRCh37_Genes_UniqueList.txt,
			   plot.title = snp_list[i],
			   file.name = paste0("mydata/", snp_list[i], ".jpg"),
         plot.type = "jpg",
			   secondary.label = FALSE,
			   ignore.lead = TRUE)`

The result is this plot:
![example_1](https://user-images.githubusercontent.com/20488558/181792393-03a83d70-65bb-47c6-8868-e9673b25d0d5.jpg)



Instead of this plot:
![example_2](https://user-images.githubusercontent.com/20488558/181792426-6a351980-b0b8-44d7-a02a-e84ee1566885.jpg)


When I change offset_bp to 100000, I can see the 3 genes closest to the SNP. If I increase offset_bp to the point where it includes more than 3 genes, the first genes start getting deleted and only the one further away get displayed. So the plot doesn't like having more than 3 genes.

Hope that makes sense, thank you.

**Comment by Geeketics** [comment]
Hi,
So there are a few patches in the code that determine how the genes are plotted. If the plot is really wide then only genes over a certain length are labelled, but all gene lines should be drawn. 
```
  if(plot.length > 5000000) {
    gene.length = 16000
  } else if(plot.length > 2000000) {
    gene.length = 12000
  } else {
    gene.length = 8000
  }
  ```

And if there are > 15 genes then there will be 5 rows of genes on the plot instead of 3 - but still all genes drawn.

The only options that change whether a gene is plotted at all are the `psuedogenes = FALSE` and `RNAs = FALSE` options, which is explained in the README.

From the code you've given I see nothing that would edit how the genes are plotted and I can't recreate the error so I can't currently see why your plot is coming out without the genes you want plotted.
